export enum TEST_ACTION_TYPES {
  SET_ONGOING_TESTS = "SET_ONGOING_TESTS",
  SET_ACTIVE_TESTS = "SET_ACTIVE_TESTS",
  SET_INACTIVE_TESTS = "SET_INACTIVE_TESTS",
  SET_EXPIRED_TESTS = "SET_EXPIRED_TESTS",
}

export interface TEST_ACTION {
  type: TEST_ACTION_TYPES;
  payload: any; // index of question
}
